server:
    extractScrapeConfigs: |
        - job_name: 'metis-services'
          kubernetes_sd_config:
              - role: service
          relabel_configs:
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_to_scrape]
                action: keep
                regex: true
