---
name: Build Test Application
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build apps job
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout main
              uses: actions/checkout@v4

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Image
              uses: docker/build-push-action@v6
              with:
                  context: ./test-apps/hello-world
                  push: true
                  #use the commit hash as the tag for the build image
                  tags: ghcr.io/${{ github.repository_owner }}/hello-wordl:ci-${{ github.sha }}

