---
name: Build Test Application
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build apps job
        runs-on: ubuntu-latest
        steps:
            - name: Placeholder Step
              run: |
                  echo "This shows the job ran"

